# Generated by Django 4.1.4 on 2022-12-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mac_address', models.CharField(max_length=30)),
                ('coordinatex', models.CharField(max_length=30)),
                ('coordinatey', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=30)),
                ('valled', models.IntegerField()),
                ('stateled', models.IntegerField()),
                ('valldr', models.IntegerField()),
                ('valldrnew', models.IntegerField()),
                ('valpir', models.IntegerField()),
                ('statepir', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartenergy.device')),
            ],
        ),
    ]
