-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 18:50:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartenergy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartenergy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartenergy` DEFAULT CHARACTER SET utf8mb4 ;
USE `smartenergy` ;

-- -----------------------------------------------------
-- Table `smartenergy`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartenergy`.`devices` (
  `iddevices` INT(11) NOT NULL,
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `macaddress` VARCHAR(18) NULL DEFAULT NULL,
  `coordinatex` VARCHAR(15) NULL DEFAULT NULL,
  `coordinatey` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`iddevices`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `smartenergy`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartenergy`.`logs` (
  `idlogs` INT(11) NOT NULL AUTO_INCREMENT,
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ipaddress` VARCHAR(16) NULL DEFAULT NULL,
  `valled` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `stateled` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `valldr` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `valldrnew` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `valpir` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `statepir` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `devices_iddevices` INT(11) NOT NULL,
  PRIMARY KEY (`idlogs`, `devices_iddevices`),
  INDEX `fk_logs_devices1_idx` (`devices_iddevices` ASC) VISIBLE,
  CONSTRAINT `fk_logs_devices1`
    FOREIGN KEY (`devices_iddevices`)
    REFERENCES `smartenergy`.`devices` (`iddevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartenergy`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartenergy`.`permissions` (
  `idpermissions` INT(11) NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idpermissions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `smartenergy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartenergy`.`users` (
  `idusers` INT(11) NOT NULL,
  `datetime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(20) NULL DEFAULT NULL,
  `permissions_idpermissions` INT(11) NOT NULL,
  PRIMARY KEY (`idusers`, `permissions_idpermissions`),
  INDEX `fk_users_permissions_idx` (`permissions_idpermissions` ASC) VISIBLE,
  CONSTRAINT `fk_users_permissions`
    FOREIGN KEY (`permissions_idpermissions`)
    REFERENCES `smartenergy`.`permissions` (`idpermissions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
